[package]
name = "arete"
version = "0.1.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A web application by Rust and React."
homepage = "https://github.com/saturn-xiv/arete"
license = "MIT"
readme = "README.md"
build = "build.rs"

[profile.release]
lto = true

[dependencies]
r2d2 = "0.8"
log = "0.4"
log4rs = "0.8"
base64 = "0.10"
rand = "0.6"
toml = "0.4"
yaml-rust = "0.4"
validator = "0.8"
validator_derive = "0.8"
serde-xml-rs = "0.3"
xml-rs = "0.8"
encoding_rs = "0.8"
reqwest = "0.9"
futures = "0.1"
tokio = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
failure = "0.1"
language-tags = "0.2"
hyper = "0.12"
juniper = "0.11"
juniper_hyper = "0.2"
r2d2_redis = "0.8"
lapin-futures = "0.18"
nix = "0.13"
eui48 = "0.4"
sodiumoxide = "0.2"
hex = "0.3"
md5 = "0.6"
git2 = "0.8"
ssh2 = "0.3"
mime = "0.3"
robots_txt = "0.6"
sitemap = "0.3"
ipnetwork = "0.13" # https://github.com/diesel-rs/diesel/blob/568d3e2420b44f5dffbd806a6c0e5e450f024394/diesel/Cargo.toml#L28 
askama = "0.8"
actix = "0.7"
actix-web = "0.7"
mustache = "*"
lazy_static = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
regex = "1"
clap = "2"
jsonwebtoken = "5"

# https://github.com/lettre/lettre/issues/312
[dependencies.lettre]
git = "https://github.com/lettre/lettre.git"

[dependencies.lettre_email]
git = "https://github.com/lettre/lettre.git"

[dependencies.cookie]
version = "0.11"
features = ["secure", "percent-encode"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.chrono-tz]
version = "0.5"
features = ["serde"]

[dependencies.rss]
version = "1"
features = ["from_url"]

[dependencies.url]
version = "1"
features=["query_encoding"]

[dependencies.uuid]
version = "0.7"
features = ["v4"]

[dependencies.openssl-sys]
version = "*"
features = ["vendored"]

[dependencies.diesel]
version = "1"
features = ["postgres", "chrono", "serde_json", "uuid", "network-address", "numeric", "r2d2", "128-column-tables"]

[package.metadata.deb]
depends = "$auto, nginx, nodejs, npm"
section = "admin"
priority = "optional"
maintainer-scripts = "scripts"
assets = [
    ["log4rs.yml", "etc/arete/", "644"],
    ["LICENSE", "usr/share/arete/", "644"],
    ["README.md", "usr/share/arete/", "644"],
    ["package.json", "usr/share/arete/", "644"],
    ["package-lock.json", "usr/share/arete/", "644"],
    ["assets/*", "usr/share/arete/assets/", "644"],
    ["dashboard/build/*", "usr/share/arete/dashboard/", "644"],
    ["dashboard/build/static/css/*", "usr/share/arete/dashboard/static/css/", "644"],
    ["dashboard/build/static/js/*", "usr/share/arete/dashboard/static/js/", "644"],
    ["target/release/arete", "usr/bin/", "755"]
]