[package]
name = "arete"
version = "0.1.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A web application by Rust and React.."
homepage = "https://github.com/saturn-xiv/arete"
license = "MIT"
edition = "2018"

[profile.release]
lto = true

[dependencies]
r2d2 = "0.8"
log = "0.4"
log4rs = "0.8"
env_logger = "0.6"
base64 = "0.10"
rand = "0.6"
toml = "0.4"
yaml-rust = "0.4"
validator = "0.8"
validator_derive = "0.8"
serde-xml-rs = "0.2"
xml-rs = "0.8"
encoding_rs = "0.8"
reqwest = "0.9"
futures = "0.1"
tokio = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
failure = "0.1"
language-tags = "0.2"
hyper = "0.10" # https://github.com/SergioBenitez/Rocket/blob/v0.4/core/http/Cargo.toml
r2d2_redis = "0.8"
lapin-futures = "0.15"
nix = "0.13"
eui48 = "0.4"
sodiumoxide = "0.2"
hex = "0.3"
md5 = "0.6"
git2 = "0.8"
ssh2 = "0.3"
mime = "0.3"
rocket = "0.4"
robots_txt = "0.6"
sitemap = "0.3"
ipnetwork = "0.13" 
mustache = "*"
lazy_static = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
regex = "1"
clap = "2"
jsonwebtoken = "5"

# https://github.com/lettre/lettre/issues/312
[dependencies.lettre]
git = "https://github.com/lettre/lettre.git"

[dependencies.lettre_email]
git = "https://github.com/lettre/lettre.git"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.multipart]
version = "0.16"
default-features = false
features = ["rocket", "server"]

[dependencies.chrono-tz]
version = "0.5"
features = ["serde"]

[dependencies.rss]
version = "1"
features = ["from_url"]

[dependencies.url]
version = "1"
features=["query_encoding"]

[dependencies.uuid]
version = "0.7"
features = ["v4"]

# https://github.com/diesel-rs/diesel/issues/1942
[dependencies.diesel]
version = "1"
features = ["postgres", "chrono", "serde_json", "uuid", "network-address", "numeric", "r2d2", "128-column-tables"]

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["tera_templates", "handlebars_templates", "diesel_postgres_pool", "redis_pool", "json", "serve", "uuid", "helmet"]
