[package]
name = "arete"
version = "0.1.1"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A web application by Rust and React."
homepage = "https://github.com/saturn-xiv/arete"
license = "MIT"
readme = "README.md"
build = "build.rs"

[profile.release]
lto = true

[features]
default = ["theme-bootstrap", "sodium", "postgresql", "redis"]
theme-bootstrap = []
theme-semantic = []
theme-bulma = []
theme-materialize = []
redis = ["rocket_contrib/redis_pool", "r2d2_redis"]
postgresql = ["rocket_contrib/diesel_postgres_pool", "diesel/postgres"]
mysql = ["rocket_contrib/diesel_mysql_pool", "diesel/mysql"]
sqlite = ["rocket_contrib/diesel_sqlite_pool", "diesel/sqlite"]
sodium = ["sodiumoxide"]

[dependencies]
r2d2 = "0.8"
log = "0.4"
log4rs = "0.8"
env_logger = "0.6"
base64 = "0.10"
rand = "0.7"
toml = "0.5"
yaml-rust = "0.4"
validator = "0.8"
validator_derive = "0.8"
serde-xml-rs = "0.3"
xml-rs = "0.8"
encoding_rs = "0.8"
futures = "0.1"
tokio = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
failure = "0.1"
language-tags = "0.2"
lapin-futures = "0.26"
nix = "0.14"
eui48 = "0.4"
hex = "0.3"
md5 = "0.6"
git2 = "0.9"
ssh2 = "0.3"
mime = "0.3"
robots_txt = "0.6"
sitemap = "0.3"
lettre = "0.9"
lettre_email = "0.9"
hyper = "0.10"
rocket = "0.4"
reqwest = "0.9"
rusoto_core = "0.40"
rusoto_credential = "0.40"
rusoto_sqs = "0.40"
rusoto_s3 = "0.40"
paho-mqtt = "0.5"
mustache = "*"
lazy_static = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
regex = "1"
csv = "1"
clap = "2"
amq-protocol-uri = "2"
mime_guess = "2"
jsonwebtoken = "5" # lock by ring
tempfile = "3"

[dependencies.multipart]
version = "0.16"
default-features = false
features = ["server"]

# lock by ring
[dependencies.cookie]
version = "0.11"
features = ["secure", "percent-encode"]

# lock by rocket
[dependencies.r2d2_redis]
version = "0.8"
optional = true

[dependencies.sodiumoxide]
version = "0.2"
optional = true

[dependencies.askama]
version = "0.8"
features = ["with-rocket"]

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json", "tera_templates", "handlebars_templates", "helmet", "uuid", "serve", "json"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.chrono-tz]
version = "0.5"
features = ["serde"]

[dependencies.rss]
version = "1"
features = ["from_url"]

[dependencies.url]
version = "1"
features=["query_encoding"]

[dependencies.uuid]
version = "0.7"
features = ["v4"]

[dependencies.zmq]
version = "0.9"
# features = ["vendored"]

[dependencies.openssl-sys]
version = "*"
features = ["vendored"]

[dependencies.diesel]
version = "1"
features = ["chrono", "serde_json", "uuid", "numeric", "r2d2", "128-column-tables"]

[dependencies.ntp]
git = "https://github.com/JeffBelgum/ntp.git"